-- Tabla: DIM_TIPO_CUENTA_BANCARIA
CREATE TABLE sgp.[DIM_TIPO_CUENTA_BANCARIA] (
  [TIPO_CUENTA_BANCARIA] varchar(10) NOT NULL,
  [TIPO_CUENTA_BANCARIA_DESCRIPCION] varchar(10) NOT NULL,
  CONSTRAINT PK_DIM_TIPO_CUENTA_BANCARIA PRIMARY KEY ([TIPO_CUENTA_BANCARIA])
);
GO

-- Datos iniciales (cargar solo si la tabla está vacía)
IF NOT EXISTS (SELECT 1 FROM sgp.[DIM_TIPO_CUENTA_BANCARIA])
BEGIN
    INSERT INTO sgp.[DIM_TIPO_CUENTA_BANCARIA] ([TIPO_CUENTA_BANCARIA], [TIPO_CUENTA_BANCARIA_DESCRIPCION])
    VALUES
      (N'A', N'AHORROS'),
      (N'C', N'CORRIENTE');
END
GO
