-- Tabla: DIM_RESGUARDOS
CREATE TABLE sgp.[DIM_RESGUARDOS] (
  [COD_DEPARTAMENTO]     varchar(2)   NOT NULL,
  [DEPARTAMENTO_NOMBRE]  varchar(240) NOT NULL,
  [COD_MUNICIPIO]        varchar(5)   NOT NULL,
  [MUNICIPIO_NOMBRE]     varchar(240) NOT NULL,
  [COD_RESGUARDO]        varchar(10)  NOT NULL,
  [RESGUARDO_NOMBRE]     varchar(240) NOT NULL,
  [NIT_TITULAR]          varchar(9)   NOT NULL,
  [FECHA_CREACION]       datetime2(0) NOT NULL CONSTRAINT DF_DIM_RESGUARDOS_FECHA_CREACION DEFAULT SYSDATETIME(),
  [FECHA_ACTUALIZACION]  datetime2(0) NOT NULL CONSTRAINT DF_DIM_RESGUARDOS_FECHA_ACTUALIZACION DEFAULT SYSDATETIME(),
  CONSTRAINT PK_DIM_RESGUARDOS PRIMARY KEY ([COD_RESGUARDO])
);
GO