-- Tabla: DIM_BENEFICIARIOS
CREATE TABLE sgp.[DIM_BENEFICIARIOS] (
  [TIPO_ID_BENEFICIARIO] varchar(2) NOT NULL,
  [ID_BENEFICIARIO] varchar(20) NOT NULL,
  [DV] varchar(1) NULL,
  [RAZON_SOCIAL] varchar(240) NOT NULL,
  [CODIGO_BANCO] varchar(4) NOT NULL,
  [CUENTA_BENEFICIARIO] varchar(20) NOT NULL,
  [TIPO_CUENTA_BENEFICIARIO] varchar(1) NOT NULL,
  CONSTRAINT PK_DIM_BENEFICIARIOS PRIMARY KEY (
    [ID_BENEFICIARIO],
    [CODIGO_BANCO],
    [CUENTA_BENEFICIARIO],
    [RAZON_SOCIAL]
  )
);
GO