-- Tabla: DIM_ENTIDADES_TERRITORIALES
CREATE TABLE sgp.[DIM_ENTIDADES_TERRITORIALES] (
  [TIPO_TITULAR] varchar(240) NOT NULL,
  [NIT] varchar(9) NOT NULL,
  [DV] varchar(1) NOT NULL,
  [RAZON_SOCIAL] varchar(240) NOT NULL,
  [NOMBRE_DEPARTAMENTO] varchar(240) NOT NULL,
  [NOMBRE_MUNICIPIO] varchar(240) NOT NULL,
  [CERTIFICADAS_EDU] varchar(240) NULL,
  [DIVIPOLA] varchar(5) NOT NULL,
  [COD_DEPARTAMENTO] varchar(2) NOT NULL,
  [COD_MUNICIPIO] varchar(3) NOT NULL,
  [LATITUD] decimal(10,6) NULL,
  [LONGITUD] decimal(10,6) NULL,
  [UBICACIÓN] varchar(240) NOT NULL,
  CONSTRAINT PK_DIM_ENTIDADES_TERRITORIALES PRIMARY KEY ([NIT])
);
GO
