-- Tabla: DIM_CUENTAS_CM

CREATE TABLE sgp.[DIM_CUENTAS_CM] (
  [DIVIPOLA] varchar(5) NOT NULL,
  [COD_DEPARTAMENTO] varchar(2) NOT NULL,
  [COD_MUNICIPIO] varchar(3) NOT NULL,
  [COD_RESGUARDO] varchar(10) NULL,
  [NIT_TITULAR] varchar(9) NOT NULL,
  [DV] varchar(1) NOT NULL,
  [TIPO_TITULAR] varchar(240) NOT NULL,
  [SECTOR] varchar(240) NOT NULL,
  [RUBRO] varchar(240) NOT NULL,
  [TIPO_CM] varchar(2) NOT NULL,
  [NUMERO_CM] varchar(20) NOT NULL,
  [TIPO_CUENTA] varchar(10) NOT NULL,
  [NIT_BANCO] varchar(9) NOT NULL,
  [CODIGO_ACH_BANCO] varchar(4) NOT NULL,
  [ID_BANCO] AS (RIGHT('000000000' + [NIT_BANCO], 9) + RIGHT('0000' + [CODIGO_ACH_BANCO], 4)) PERSISTED,
  [FECHA_CREACION] date NOT NULL,
  [FECHA_ACTUALIZACION] date NOT NULL,
  CONSTRAINT PK_DIM_CUENTAS_CM PRIMARY KEY ([NUMERO_CM]),
  CONSTRAINT FK_DIM_CUENTAS_CM_COD_RESGUARDO__DIM_RESGUARDOS_COD_RESGUARDO FOREIGN KEY ([COD_RESGUARDO]) REFERENCES sgp.[DIM_RESGUARDOS] ([COD_RESGUARDO]),
  CONSTRAINT FK_DIM_CUENTAS_CM_NIT_TITULAR__DIM_TITULARES_NIT FOREIGN KEY ([NIT_TITULAR]) REFERENCES sgp.[DIM_TITULARES] ([NIT]),
  CONSTRAINT FK_DIM_CUENTAS_CM_TIPO_CM__DIM_TIPO_CM_TIPO_CM FOREIGN KEY ([TIPO_CM]) REFERENCES sgp.[DIM_TIPO_CM] ([TIPO_CM]),
  CONSTRAINT FK_DIM_CUENTAS_CM_ID_BANCO__DIM_BANCOS_ID_BANCO FOREIGN KEY ([ID_BANCO]) REFERENCES sgp.[DIM_BANCOS] ([ID_BANCO])
);
GO