-- Tabla: FACT_MOVIMIENTOS_CMP
-- Tabla: FACT_MOVIMIENTOS_CMP
CREATE TABLE sgp.[FACT_MOVIMIENTOS_CMP] (
  [ID_MOV_CMP] varchar(20) NOT NULL,
  [TIPO_CMP] varchar(2) NOT NULL,
  [NUMERO_CMP] varchar(20) NOT NULL,
  [NUMERO_CM_PRINCIPAL] varchar(20) NULL,
  [FECHA_MOVIMIENTO] date NOT NULL,
  [TIPO_MOVIMIENTO] varchar(3) NOT NULL,
  [DESCRIPCION_MOVIMIENTO] varchar(240) NULL,
  [VALOR] decimal(20,2) NOT NULL,
  [TIPO_ID_BENEFICIARIO] varchar(2) NOT NULL,
  [ID_BENEFICIARIO] varchar(9) NOT NULL,
  [DV] varchar(1) NULL,
  [RAZON_SOCIAL] varchar(240) NULL,
  [CODIGO_SERVICIO] varchar(20) NULL,
  [CUS] varchar(240) NULL,

  CONSTRAINT PK_FACT_MOVIMIENTOS_CMP PRIMARY KEY ([ID_MOV_CMP]),
  CONSTRAINT FK_FACT_MOVIMIENTOS_CMP_TIPO_CMP__DIM_TIPO_CMP_TIPO_CMP
    FOREIGN KEY ([TIPO_CMP])
    REFERENCES sgp.[DIM_TIPO_CMP] ([TIPO_CMP]),
  CONSTRAINT FK_FACT_MOVIMIENTOS_CMP_NUMERO_CMP__DIM_CUENTAS_CMP_NUMERO_CMP
    FOREIGN KEY ([NUMERO_CMP])
    REFERENCES sgp.[DIM_CUENTAS_CMP] ([NUMERO_CMP]),
  CONSTRAINT FK_FACT_MOVIMIENTOS_CMP_TIPO_MOVIMIENTO__DIM_TIPO_MOVIMIENTO_TIPO_MOVIMIENTO
    FOREIGN KEY ([TIPO_MOVIMIENTO])
    REFERENCES sgp.[DIM_TIPO_MOVIMIENTO] ([TIPO_MOVIMIENTO]),
  CONSTRAINT FK_FACT_MOVIMIENTOS_CMP_TIPO_ID_BENEFICIARIO__DIM_TIPO_ID_BENEFICIARIO_TIPO_IDENTIFICACION_BENEFICIARIO
    FOREIGN KEY ([TIPO_ID_BENEFICIARIO])
    REFERENCES sgp.[DIM_TIPO_ID_BENEFICIARIO] ([TIPO_IDENTIFICACION_BENEFICIARIO])
);
GO