-- Tabla: FACT_MOVIMIENTOS_CM
CREATE TABLE sgp.[FACT_MOVIMIENTOS_CM] (
  [ID_MOV_CM] varchar(20) NOT NULL,
  [TIPO_CM] varchar(2) NOT NULL,
  [NUMERO_CM] varchar(20) NOT NULL,
  [FECHA_MOVIMIENTO] date NOT NULL,
  [TIPO_MOVIMIENTO] varchar(3) NOT NULL,
  [DESCRIPCION_MOVIMIENTO] varchar(240) NULL,
  [VALOR] decimal(20,2) NOT NULL,
  [TIPO_ID_BENEFICIARIO] varchar(2) NOT NULL,
  [ID_BENEFICIARIO] varchar(20) NOT NULL,
  [DV] varchar(1) NULL,
  [RAZON_SOCIAL] varchar(240) NULL,
  [CODIGO_BANCO] varchar(4) NOT NULL,
  [CUENTA_BENEFICIARIO] varchar(20) NOT NULL,
  [TIPO_CUENTA_BENEFICIARIO] varchar(1) NOT NULL,
  CONSTRAINT PK_FACT_MOVIMIENTOS_CM PRIMARY KEY ([ID_MOV_CM]),
  CONSTRAINT FK_FACT_MOVIMIENTOS_CM_TIPO_CM__DIM_TIPO_CM_TIPO_CM
    FOREIGN KEY ([TIPO_CM]) REFERENCES sgp.[DIM_TIPO_CM] ([TIPO_CM]),
  CONSTRAINT FK_FACT_MOVIMIENTOS_CM_NUMERO_CM__DIM_CUENTAS_CM_NUMERO_CM
    FOREIGN KEY ([NUMERO_CM]) REFERENCES sgp.[DIM_CUENTAS_CM] ([NUMERO_CM]),
  CONSTRAINT FK_FACT_MOVIMIENTOS_CM_TIPO_MOVIMIENTO__DIM_TIPO_MOVIMIENTO_TIPO_MOVIMIENTO
    FOREIGN KEY ([TIPO_MOVIMIENTO]) REFERENCES sgp.[DIM_TIPO_MOVIMIENTO] ([TIPO_MOVIMIENTO])
);
GO