-- Tabla: REF_TIPO_MOV_TIPO_CM
-- Nota: Tabla de referencia normativa. Puede omitirse si el mapeo se gestiona exclusivamente con DIM_TIPO_CM y DIM_TIPO_CMP.
CREATE TABLE sgp.[REF_TIPO_MOV_TIPO_CM] (
  [TIPO_CM] varchar(2) NOT NULL,
  [SECTOR] varchar(240) NOT NULL,
  [TIPO_MOVIMIENTO] varchar(3) NOT NULL,
  [DESCRIPCION_MOVIMIENTO] varchar(240) NULL,
  CONSTRAINT FK_REF_TIPO_MOV_TIPO_CM_TIPO_CM__DIM_TIPO_CM_TIPO_CM FOREIGN KEY ([TIPO_CM]) REFERENCES sgp.[DIM_TIPO_CM] ([TIPO_CM])
);
GO

-- Datos iniciales (cargar solo si la tabla está vacía)
IF NOT EXISTS (SELECT 1 FROM sgp.[REF_TIPO_MOV_TIPO_CM])
BEGIN
    INSERT INTO sgp.[REF_TIPO_MOV_TIPO_CM] ([TIPO_CM], [SECTOR], [TIPO_MOVIMIENTO], [DESCRIPCION_MOVIMIENTO])
    VALUES
      (N'PG', N'MHCP', 100, N'Ingreso'),
      (N'PG', N'MHCP', 110, N'Rendimientos Financieros'),
      (N'PG', N'MHCP', 120, N'Reintegros bancarios'),
      (N'PG', N'MHCP', 270, N'Egresos por medidas cautelares de embargo'),
      (N'PG', N'MHCP', 310, N'Egreso Libre Inversión'),
      (N'PG', N'MHCP', 311, N'Egreso Recreación y Deporte'),
      (N'PG', N'MHCP', 312, N'Egreso Cultura'),
      (N'PG', N'MHCP', 313, N'Egreso Libre Destinación'),
      (N'PG', N'MHCP', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'PG', N'MHCP', 500, N'Saldo Inicial cuenta'),
      (N'PG', N'MHCP', 600, N'Saldo Final cuenta'),
      (N'ED', N'MHCP', 100, N'Ingreso'),
      (N'ED', N'MHCP', 110, N'Rendimientos Financieros'),
      (N'ED', N'MHCP', 120, N'Reintegros bancarios'),
      (N'ED', N'MHCP', 270, N'Egresos por medidas cautelares de embargo'),
      (N'ED', N'MHCP', 311, N'Egreso Recreación y Deporte'),
      (N'ED', N'MHCP', 312, N'Egreso Cultura'),
      (N'ED', N'MHCP', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'ED', N'MHCP', 500, N'Saldo Inicial cuenta'),
      (N'ED', N'MHCP', 600, N'Saldo Final cuenta'),
      (N'AE', N'MHCP', 100, N'Ingreso'),
      (N'AE', N'MHCP', 110, N'Rendimientos Financieros'),
      (N'AE', N'MHCP', 120, N'Reintegros bancarios'),
      (N'AE', N'MHCP', 270, N'Egresos por medidas cautelares de embargo'),
      (N'AE', N'MHCP', 320, N'Egreso Asignación Alimentación Escolar, Municipios Ribereños, Resguardos Indigenas, Primera Infancia'),
      (N'AE', N'MHCP', 321, N'Egreso Programa de Alimentación Escolar - PAE.'),
      (N'AE', N'MHCP', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'AE', N'MHCP', 500, N'Saldo Inicial cuenta'),
      (N'AE', N'MHCP', 600, N'Saldo Final cuenta'),
      (N'MR', N'MHCP', 100, N'Ingreso'),
      (N'MR', N'MHCP', 110, N'Rendimientos Financieros'),
      (N'MR', N'MHCP', 120, N'Reintegros bancarios'),
      (N'MR', N'MHCP', 270, N'Egresos por medidas cautelares de embargo'),
      (N'MR', N'MHCP', 320, N'Egreso Asignación Alimentación Escolar, Municipios Ribereños, Resguardos Indigenas, Primera Infancia'),
      (N'MR', N'MHCP', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'MR', N'MHCP', 500, N'Saldo Inicial cuenta'),
      (N'MR', N'MHCP', 600, N'Saldo Final cuenta'),
      (N'PI', N'MHCP', 100, N'Ingreso'),
      (N'PI', N'MHCP', 110, N'Rendimientos Financieros'),
      (N'PI', N'MHCP', 120, N'Reintegros bancarios'),
      (N'PI', N'MHCP', 270, N'Egresos por medidas cautelares de embargo'),
      (N'PI', N'MHCP', 320, N'Egreso Asignación Alimentación Escolar, Municipios Ribereños, Resguardos Indigenas, Primera Infancia'),
      (N'PI', N'MHCP', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'PI', N'MHCP', 500, N'Saldo Inicial cuenta'),
      (N'PI', N'MHCP', 600, N'Saldo Final cuenta'),
      (N'RI', N'MHCP', 100, N'Ingreso'),
      (N'RI', N'MHCP', 110, N'Rendimientos Financieros'),
      (N'RI', N'MHCP', 120, N'Reintegros bancarios'),
      (N'RI', N'MHCP', 270, N'Egresos por medidas cautelares de embargo'),
      (N'RI', N'MHCP', 320, N'Egreso Asignación Alimentación Escolar, Municipios Ribereños, Resguardos Indigenas, Primera Infancia'),
      (N'RI', N'MHCP', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'RI', N'MHCP', 500, N'Saldo Inicial cuenta'),
      (N'RI', N'MHCP', 600, N'Saldo Final cuenta'),
      (N'AP', N'MVCT', 100, N'Ingreso'),
      (N'AP', N'MVCT', 110, N'Rendimientos Financieros'),
      (N'AP', N'MVCT', 120, N'Reintegros bancarios'),
      (N'AP', N'MVCT', 270, N'Egresos por medidas cautelares de embargo'),
      (N'AP', N'MVCT', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'AP', N'MVCT', 410, N'Egresos gastos de inversión en acueducto, alcantarillado y aseo'),
      (N'AP', N'MVCT', 420, N'Egresos para el pago de subsidios en acueducto, alcantarillado y aseo'),
      (N'AP', N'MVCT', 430, N'Egresos Transeferencias al PDA'),
      (N'AP', N'MVCT', 440, N'Egresos para el servicio de la deuda Cuenta Maestra Agua Potable y Saneamiento Básico'),
      (N'AP', N'MVCT', 460, N'Otros Egresos Cuenta Maestra Agua Potable y Saneamiento Básico'),
      (N'AP', N'MVCT', 470, N'Egreso Impuestos Cuenta Maestra Agua Poable y Saneamiento Básico'),
      (N'AP', N'MVCT', 500, N'Saldo Inicial cuenta'),
      (N'AP', N'MVCT', 600, N'Saldo Final cuenta'),
      (N'SN', N'MEN', 100, N'Ingreso'),
      (N'SN', N'MEN', 110, N'Rendimientos Financieros'),
      (N'SN', N'MEN', 120, N'Reintegros bancarios'),
      (N'SN', N'MEN', 270, N'Egresos por medidas cautelares de embargo'),
      (N'SN', N'MEN', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'SN', N'MEN', 510, N'Egreso Prestación del servicio Nómina Docente, Directiva Docente y administrativa'),
      (N'SN', N'MEN', 520, N'Egreso Contratación del servicio Educativo'),
      (N'SN', N'MEN', 530, N'Egreso Contratación de aseo y vigilancia'),
      (N'SN', N'MEN', 540, N'Egreso Gastos Administrativos distintos de Nómina Docente, Directiva Docente y administrativa'),
      (N'SN', N'MEN', 550, N'Egreso NEE'),
      (N'SN', N'MEN', 560, N'Egreso Conectividad'),
      (N'SN', N'MEN', 570, N'Egreso Internados'),
      (N'SN', N'MEN', 580, N'Egreso Mejoramiento de la Calidad'),
      (N'SN', N'MEN', 500, N'Saldo Inicial cuenta'),
      (N'SN', N'MEN', 600, N'Saldo Final cuenta'),
      (N'SO', N'MEN', 100, N'Ingreso'),
      (N'SO', N'MEN', 110, N'Rendimientos Financieros'),
      (N'SO', N'MEN', 120, N'Reintegros bancarios'),
      (N'SO', N'MEN', 270, N'Egresos por medidas cautelares de embargo'),
      (N'SO', N'MEN', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'SO', N'MEN', 510, N'Egreso Prestación del servicio Nómina Docente, Directiva Docente y administrativa'),
      (N'SO', N'MEN', 520, N'Egreso Contratación del servicio Educativo'),
      (N'SO', N'MEN', 530, N'Egreso Contratación de aseo y vigilancia'),
      (N'SO', N'MEN', 540, N'Egreso Gastos Administrativos distintos de Nómina Docente, Directiva Docente y administrativa'),
      (N'SO', N'MEN', 550, N'Egreso NEE'),
      (N'SO', N'MEN', 560, N'Egreso Conectividad'),
      (N'SO', N'MEN', 570, N'Egreso Internados'),
      (N'SO', N'MEN', 580, N'Egreso Mejoramiento de la Calidad'),
      (N'SO', N'MEN', 500, N'Saldo Inicial cuenta'),
      (N'SO', N'MEN', 600, N'Saldo Final cuenta'),
      (N'CA', N'MEN', 100, N'Ingreso'),
      (N'CA', N'MEN', 110, N'Rendimientos Financieros'),
      (N'CA', N'MEN', 120, N'Reintegros bancarios'),
      (N'CA', N'MEN', 270, N'Egresos por medidas cautelares de embargo'),
      (N'CA', N'MEN', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'CA', N'MEN', 510, N'Egreso Prestación del servicio Nómina Docente, Directiva Docente y administrativa'),
      (N'CA', N'MEN', 520, N'Egreso Contratación del servicio Educativo'),
      (N'CA', N'MEN', 530, N'Egreso Contratación de aseo y vigilancia'),
      (N'CA', N'MEN', 540, N'Egreso Gastos Administrativos distintos de Nómina Docente, Directiva Docente y administrativa'),
      (N'CA', N'MEN', 550, N'Egreso NEE'),
      (N'CA', N'MEN', 560, N'Egreso Conectividad'),
      (N'CA', N'MEN', 570, N'Egreso Internados'),
      (N'CA', N'MEN', 580, N'Egreso Mejoramiento de la Calidad'),
      (N'CA', N'MEN', 500, N'Saldo Inicial cuenta'),
      (N'CA', N'MEN', 600, N'Saldo Final cuenta'),
      (N'MT', N'MEN', 100, N'Ingreso'),
      (N'MT', N'MEN', 110, N'Rendimientos Financieros'),
      (N'MT', N'MEN', 120, N'Reintegros bancarios'),
      (N'MT', N'MEN', 270, N'Egresos por medidas cautelares de embargo'),
      (N'MT', N'MEN', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'MT', N'MEN', 510, N'Egreso Prestación del servicio Nómina Docente, Directiva Docente y administrativa'),
      (N'MT', N'MEN', 520, N'Egreso Contratación del servicio Educativo'),
      (N'MT', N'MEN', 530, N'Egreso Contratación de aseo y vigilancia'),
      (N'MT', N'MEN', 540, N'Egreso Gastos Administrativos distintos de Nómina Docente, Directiva Docente y administrativa'),
      (N'MT', N'MEN', 550, N'Egreso NEE'),
      (N'MT', N'MEN', 560, N'Egreso Conectividad'),
      (N'MT', N'MEN', 570, N'Egreso Internados'),
      (N'MT', N'MEN', 580, N'Egreso Mejoramiento de la Calidad'),
      (N'MT', N'MEN', 500, N'Saldo Inicial cuenta'),
      (N'MT', N'MEN', 600, N'Saldo Final cuenta'),
      (N'GR', N'MEN', 100, N'Ingreso'),
      (N'GR', N'MEN', 110, N'Rendimientos Financieros'),
      (N'GR', N'MEN', 120, N'Reintegros bancarios'),
      (N'GR', N'MEN', 270, N'Egresos por medidas cautelares de embargo'),
      (N'GR', N'MEN', 360, N'Egreso por costos o gastos bancarios cuando haya lugar, en este caso el beneficiario es el mismo banco'),
      (N'GR', N'MEN', 510, N'Egreso Prestación del servicio Nómina Docente, Directiva Docente y administrativa'),
      (N'GR', N'MEN', 520, N'Egreso Contratación del servicio Educativo'),
      (N'GR', N'MEN', 530, N'Egreso Contratación de aseo y vigilancia'),
      (N'GR', N'MEN', 540, N'Egreso Gastos Administrativos distintos de Nómina Docente, Directiva Docente y administrativa'),
      (N'GR', N'MEN', 550, N'Egreso NEE'),
      (N'GR', N'MEN', 560, N'Egreso Conectividad'),
      (N'GR', N'MEN', 570, N'Egreso Internados'),
      (N'GR', N'MEN', 580, N'Egreso Mejoramiento de la Calidad'),
      (N'GR', N'MEN', 500, N'Saldo Inicial cuenta'),
      (N'GR', N'MEN', 600, N'Saldo Final cuenta');
END
GO
